eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 9007

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: wordladder
        uri: lb://service-wordladder
        predicates:
        - Path=/wordLadder/**
        filters:
        - StripPrefix=1