eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: client1
        uri: lb://client1
        predicates:
        - Path=/client1/**
        filters:
        - StripPrefix=1
      - id: client2
        uri: lb://client2
        predicates:
        - Path=/client2/**
        filters:
        - StripPrefix=1